### ISSUE TITLE
Improvement: Increase maximum number of character for button

### ISSUE THREAD

**Issue by TomoTsuyuki** [reskit/moodle-tiny_c4l#10]
Currently, we can use 15 characters maximum for button name.

It's not enough some cases and I would like to increase the limit.

**Comment by reskit** [comment]
Hi @TomoTsuyuki,

Our design is intended to work with Boost theme and therefore we forced 15 characters to allow the icon and the full text to be displayed within the button without problems, maybe your theme/font-family/font-size allow more characters to be displayed.

We are not going to change this behavior in our plugin but we encourage anyone who wants to modify the interface to do it in their own site.

Cheers
