### ISSUE TITLE
Translation is not being used in main component

### ISSUE THREAD

**Issue by krmu** [reskit/moodle-tiny_c4l#5]
After translating this plugin we still have issue with using trnaslation in main component.

Please check the image.
![image](https://github.com/reskit/moodle-tiny_c4l/assets/53869559/4215272e-d739-4d1a-8a5b-23cb14a8be5f)
As we see in the image, we have translated this component part, but after using it in editor, it still shows the english translation that is wrong.

![image](https://github.com/reskit/moodle-tiny_c4l/assets/53869559/ad04fe50-5431-4516-a226-0e355478030b)

Thank you!

**Comment by krmu** [comment]
Adding probably the line that is responsible of this.
https://github.com/reskit/moodle-tiny_c4l/blob/e3a4e759f4258224f1d4be6f7e530970a7c8b607/amd/src/components.js#L217C52-L217C69

**Comment by reskit** [comment]
Hi @krmu,

I've fixed the Learning outcomes string.

Due date and Grading value had the same problem and I've fixed them too.

 Thanks for reporting the bug!

Today or tomorrow a new version will be released,

Cheers!
