### ISSUE TITLE
Feature request: Allow admins to create own components

### ISSUE THREAD

**Issue by ralfhilg** [reskit/moodle-tiny_c4l#7]
It should be possible that admins can addown components.

**Comment by reskit** [comment]
Hi @ralfhilg,

This feature is in our roadmap.  It has some problems to implement due to Moodle restrictions with CSS styles.

In case we can solve the CSS styles issue and some other minor problems (icons, variants, ...) I hope sooner than later this feature will be available.

Cheers.
