### ISSUE TITLE
Improvement: Increase maximum number of custom components

### ISSUE THREAD

**Issue by TomoTsuyuki** [reskit/moodle-tiny_c4l#8]
Currently, we can make 12 custom components.

It's not enough some cases and I would like to increase the limit.

**Comment by reskit** [comment]
Hi @TomoTsuyuki,

Thanks for your proposal.

We are planning to increase the maximum number of custom components, but in a different way. We think 12 components per category are just fine to navigate through them.

In the next version, we want to allow users to create new categories with a maximum of 12 elements for each one.

Hope next version will come soon.

**Comment by golenkovm** [comment]
Thanks @reskit 

Would it be possible to keep the current issue open until the enhancement is implemented? Or create a separate one for your implementation approach? Having an open issue would help to track progress and follow up on it if needed.

Kind regards,
Misha

**Comment by dmitriim** [comment]
Hi @reskit 

As far as I understand core purpose of C4L is to provide rich, visual building blocks for learning content. Educators use very different approaches, so having access to a wide variety of components supports differentiated and creative teaching. A limit could force institutions to choose a narrow subset of components, which may restrict instructional design and pretty much force institution to find alternatives for this plugin as supporting its fork can not be feasible.
